name: Build Server Linux Image Seqera R-IDE

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Original tag to build Seqera R IDE from'
        required: true
        type: string
        default: 'v2025.05.0+496'

jobs:
  apply-patches:
    name: Apply Patches and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create New Branch from Tag
        run: |
          git fetch --tags
          git checkout ${{ inputs.tag }}
          NEW_BRANCH="seqera/${{ inputs.tag }}"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          git checkout -b $NEW_BRANCH

      - name: Fetch Patches from default branch
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout origin/${{ github.event.repository.default_branch }} -- PATCH

      - name: Apply Patches
        run: |
          for patch in PATCH/*.patch; do
            git apply "$patch" || exit 1
          done

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Apply patch - seqera customization"
          git push --set-upstream origin ${{ env.NEW_BRANCH }}

      - name: Create New Tag
        id: create-tag
        run: |
          NEW_TAG=$(echo "${{ env.NEW_BRANCH }}" | sed 's/\//-/g')
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.create-tag.outputs.new_tag }}
          release_name: Release ${{ steps.create-tag.outputs.new_tag }}
          body: |
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_tag: ${{ steps.create-tag.outputs.new_tag }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}

  build-server-linux:
    name: Build Server Linux
    needs: [apply-patches]
    strategy:
      matrix:
        arch: [ arm64, amd64 ]

    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - name: Check Architecture
        run: uname -m
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.apply-patches.outputs.new_tag }}

      - name: Install Dependencies
        run: |
          cd dependencies/linux
          chmod +x ./install-dependencies-debian
          ./install-dependencies-debian

      - name: Build Server Package
        run: |
          cd package/linux
          chmod +x ./make-server-package
          ./make-server-package DEB clean

      - name: Locate .deb File
        id: locate-deb
        run: |
          ls -ls package/linux/build-Server-DEB
          DEB_FILE=$(find package/linux/build-Server-DEB -maxdepth 1 -name "*.deb" -type f | tr '\n' ' ')
          if [ -z "$DEB_FILE" ]; then
            echo "Error: No .deb file found!"
            exit 1
          fi
          echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT

      - name: Upload .deb File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.apply-patches.outputs.upload_url }}
          asset_name: ${{ matrix.arch }}.deb
          asset_path: ${{ steps.locate-deb.outputs.deb_file }}
          asset_content_type: application/vnd.debian.binary-package