name: FAKE Build Server Linux Image Seqera R-IDE

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Original tag to build Seqera R IDE from'
        required: true
        type: string
        default: 'v2025.05.0+496'

jobs:
  apply-patches:
    name: Apply Patches and Create Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create New Branch from Tag
        run: |
          git fetch --tags
          git checkout ${{ inputs.tag }}
          NEW_BRANCH="seqera/${{ inputs.tag }}"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          git checkout -b $NEW_BRANCH

      - name: Fetch Patches from seqera/test
        run: |
          git fetch origin seqera/test
          git checkout origin/seqera/test -- PATCH

      - name: Apply Patches
        run: |
          for patch in PATCH/*.patch; do
            git apply "$patch" || exit 1
          done

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Apply patch - seqera customization"
          git push --set-upstream origin ${{ env.NEW_BRANCH }}

      - name: Create New Tag
        id: create-tag
        run: |
          NEW_TAG=$(echo "${{ env.NEW_BRANCH }}" | sed 's/\//-/g')
          echo "new_tag=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
    outputs:
      new_tag: ${{ steps.create-tag.outputs.new_tag }}

  build-server-linux:
    name: Build Server Linux
    runs-on: ubuntu-24.04
    needs: [apply-patches]

    strategy:
      matrix:
        arch: [arm64, amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.apply-patches.outputs.new_tag }}

      - name: Set up Environment Variables
        run: |
          echo "PACKAGE_OS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Ensure fallocate is available
        run: |
          if ! command -v fallocate &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y util-linux
          fi

      - name: Build Server Package MOCK
        run: |
          mkdir -p package/linux/build-Server-DEB
          fallocate -l 1M package/linux/build-Server-DEB/fake-package.deb

      - name: Locate .deb File
        id: locate-deb
        run: |
          DEB_FILE=$(find package/linux/build-Server-DEB -maxdepth 1 -name "*.deb" -type f | tr '\n' ' ')
          if [ -z "$DEB_FILE" ]; then
            echo "Error: No .deb file found!"
              exit 1
          fi
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            echo "file_amd64=$DEB_FILE" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.arch }}" = "arm64" ]; then
            echo "file_arm64=$DEB_FILE" >> $GITHUB_OUTPUT
          else
            echo "Error: Unsupported architecture '${{ matrix.arch }}'!"
          exit 1
          fi

      - name: Upload .deb File
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}.deb
          path: ${{ matrix.arch == 'amd64' && steps.locate-deb.outputs.file_amd64 || steps.locate-deb.outputs.file_arm64 }}
    outputs:
      file_${{ matrix.arch }}: ${{ steps.locate-deb.outputs.file_${{ matrix.arch }} }}

  create-release:
    name: Create Server Prerelease
    needs: [build-server-linux]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        id: create-gh-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.apply-patches.outputs.new_tag }}
          release_name: Release ${{ needs.apply-patches.outputs.new_tag }}
          body: |
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload arm64 File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-gh-release.outputs.upload_url }}
          asset_name: arm64.deb
          asset_path: ${{ needs.build-server-linux.outputs.file_arm64 }}
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload amd64 File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-gh-release.outputs.upload_url }}
          asset_name: amd64.deb
          asset_path: ${{ needs.build-server-linux.outputs.file_amd64 }}
          asset_content_type: application/vnd.debian.binary-package