name: Apply Patches and Push Branch

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to base the new branch on'
        required: true
        type: string

jobs:
  apply-patches:
    name: Apply Patches and Push Branch
    runs-on: ubuntu-latest
    permissions:
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Configure Git Author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create New Branch from Tag
        run: |
          git fetch --tags
          git checkout ${{ inputs.tag }}
          NEW_BRANCH="seqera/${{ inputs.tag }}"
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
          git checkout -b $NEW_BRANCH

      - name: Fetch Patches from seqera/test
        run: |
          git fetch origin seqera/test
          git checkout origin/seqera/test -- PATCH

      - name: Apply Patches
        run: |
          for patch in PATCH/*.patch; do
            git apply "$patch" || exit 1
          done

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Apply patch - seqera customization"
          git push --set-upstream origin ${{ env.NEW_BRANCH }}